language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq pkg-config check doxygen

script:
    - ./bootstrap
    - ./configure
    - echo Build using $(nproc) parallel jobs
    - make -j$(nproc)
    - make check
    - make distcheck

